### ISSUE TITLE
Allow installation of DPMJET without surrounding impy installation

### ISSUE THREAD

**Issue by wdconinc** [DPMJET/DPMJET#13]
Currently, a `make install` on my system results in:
```console
cat: ../rangen.fpp: No such file or directory
cat: ../logging.f: No such file or directory
make: *** [Makefile:201: _dpmjetIII193.pyf] Error 1
```
(Note: `make all` succeeds fine; this is just the `install` target.)

This appears to be caused by the following targets (around line 200 in the Makefile, reordered here for readability):
```makefile
install: $(pylib)

$(pylib): _dpmjetIII193.pyf $(DPMJET_OBJS) $(PHOJET_OBJS) $(PYTHIA_OBJS) $(DUMMY_OBJS) $(IMPY_RANGEN_OBJ) $(IMPY_LOGGING_OBJ)

_dpmjetIII193.pyf:
        $(CAT_COMMAND) $(PYF_SRCS) $(IMPY_RANGEN_SRC) $(IMPY_LOGGING_SRC) > f2pytemp.f
```
This means that an installation will require `$(IMPY_RANGEN_SRC) $(IMPY_LOGGING_SRC)` to exist, defined as `../rangen.fpp ../logging.f`.

This is fine when installing DPMJET as a submodule of `impy`, but it fails on standalone checkouts.

**Comment by afedynitch** [comment]
Hi,

please see my comment on your PR #12 that the build of the python interface via make is now deprecated.

This task will be handled by our new build system in impy. If you use the default target `all: exe` then everything should work from the master branch. `make install` has no purpose outside of impy. Also, I recommend using the releases.

Is there any reason you want to build the python libs without impy?

**Comment by afedynitch** [comment]
Doesn't seem to be relevant anymore. `impy` is now [Chromo](https://github.com/impy-project/chromo).
