### ISSUE TITLE
LHE output

### ISSUE THREAD

**Issue by michael-pitt** [DPMJET/DPMJET#18]
Hello,

Can the LHE option be added as an output to the standalone package?

Regards,
Michael

**Comment by afedynitch** [comment]
Hi Michael,

we have transitioned to [Chromo](https://github.com/impy-project/chromo) as an interface to the code. I will maintain the present featureset of the file interface but won't add additional features. If you like, you can open this issue in Chromo, then we may have a look at how to implement this.

Cheers,
Anatoli
