### ISSUE TITLE
DPMJET getting stuck in gamma-Nucleus process

### ISSUE THREAD

**Issue by stahlleiton** [DPMJET/DPMJET#19]
While attempting to interface the Starlight generator (for photon spectra) with DPMJET 19 (for photon-nucleus events), we  encountered a problem where DPMJET is getting stuck after being called.

The problem also appears when running standalone DPMJET with the example gamma-Carbon input card (distributed with the DPMJET package). It prints some initial output but then keeps running indefinitely without producing any results.

The test was performed with DPMJET [v19.3.6](https://github.com/DPMJET/DPMJET/releases/tag/v19.3.6) and the program was called using:
./bin/DPMJET < examples/dpmjet/gC.inp .
and the output is attached [here](https://github.com/DPMJET/DPMJET/files/13689639/out.txt).

@afedynitch @SpencerKlein @lbarbele

**Comment by stahlleiton** [comment]
Including @SpencerKlein and @lbarbele , who also encountered this problem

**Comment by afedynitch** [comment]
Hi.

Sorry for taking that long. Please try the branch fix_gamma_A and let me know if there are more problems I should be aware of.

Also, if DPMJET is part of an official Starlight, it would be desirable if Starlight distributes an official release. If there are specific features or conditional compilation blocks needed this can certainly be done.

**Comment by SpencerKlein** [comment]
Hi Anatoli:

The main branch of STARlight has been updated to work with the new version of DPMJET, using a fix provided by Andre Stahl (thanks!).   There was one user who wanted to maintain the option to run the older version of DPMJET, but he is satisfied to keep this as a private version (and it would be possible to check out an old version of STARlight if needed).  

The "official release" of STARlight is the main branch in our github repository, https://github.com/STARlightsim/STARlight  Unfortunately, the versioning system that we used on HEPFORGE doesn't really work on github, where there is no master repository, but we try to tag versions more frequently, and I will make a tagged version on request.  The README file includes instructions for using DPMJET, and the DPMJET interface code is available at

https://github.com/STARlightsim/STARlight/tree/main/dpmjet

Please let me know if you have (or hear of) any problems, or have any other suggestions for improvement.

Spencer

**Comment by afedynitch** [comment]
Thanks, Spencer for letting me know that the code works in starlight. 

The dpmjet interface looks very clean.

**Comment by stahlleiton** [comment]
Ok. Then I will proceed to close this issue by the end of the day.
