### ISSUE TITLE
Please remove auto-generated file and update version referenced in impy

### ISSUE THREAD

**Issue by HDembinski** [DPMJET/DPMJET#9]
This file was accidentally committed and needs to be deleted:

https://github.com/HDembinski/DPMJET/blob/master/common/dpmjetIII193.pyf

**Comment by afedynitch** [comment]
The pyf files are meant to be distributed because they don't change very frequently. Sometimes there can be parsing problems depending on OS and numpy version. It's just safer to keep them.

**Comment by afedynitch** [comment]
For the updated versions, [see this pending PR](https://github.com/impy-project/impy/pull/25)

**Comment by HDembinski** [comment]
Ok, I will use the pre-generated pyf files then.
